# Generated by Django 4.2.28 on 2026-03-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_organization_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_provider',
            field=models.CharField(choices=[('email', 'Email'), ('42', '42 OAuth')], default='email', max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar42',
            field=models.URLField(blank=True, default='', help_text='42 profile image URL', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='campus42',
            field=models.CharField(blank=True, default='', help_text='42 campus name (e.g. 1337)', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='login42',
            field=models.CharField(blank=True, help_text='42 Intra login (e.g. abourji)', max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='needs_role',
            field=models.BooleanField(default=False, help_text="True if 42 user hasn't chosen role yet"),
        ),
    ]
